# DFW Food Access

In [11]:
import pandas as pd
import geopandas
import folium
import requests
from bs4 import BeautifulSoup

In [2]:
# IRS SOI Individual Income Tax ZIP Code Data from 2017
irs_soi = pd.read_csv('data/irs-zipcode-2017/17zpallagi.csv')
# GeoJSON zipcode boundaries for Texas
tx_geo = geopandas.read_file('data/State-zip-code-GeoJSON-master/tx_texas_zip_codes_geo.min.json')

In [4]:
tx_geo.head()

,STATEFP10,ZCTA5CE10,GEOID10,CLASSFP10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,PARTFLG10,geometry
0,48,75801,4875801,B5,G6350,S,555807428,6484251,+31.7345202,-095.5313809,N,"POLYGON ((-95.68072 31.72800, -95.68085 31.728..."
1,48,75839,4875839,B5,G6350,S,381863557,3928555,+31.6066930,-095.5833403,N,"POLYGON ((-95.66269 31.64586, -95.66242 31.645..."
2,48,78336,4878336,B5,G6350,S,126923194,31624523,+27.9269126,-097.1777757,N,"POLYGON ((-97.19642 27.91194, -97.19618 27.912..."
3,48,76389,4876389,B5,G6350,S,515265783,10157866,+33.5126278,-098.4576268,N,"MULTIPOLYGON (((-98.37035 33.44176, -98.37820 ..."
4,48,76310,4876310,B5,G6350,S,465637930,24888388,+33.7990847,-098.5098400,N,"POLYGON ((-98.50723 33.84419, -98.50235 33.844..."

In [7]:
us_geo = geopandas.read_file('data/Census-ZCTA/tl_2019_us_zcta510.shp')

In [14]:
us_geo.head()

,ZCTA5CE10,GEOID10,CLASSFP10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,43451,43451,B5,G6350,S,63484186,157689,+41.3183010,-083.6174935,"POLYGON ((-83.70873 41.32733, -83.70815 41.327..."
1,43452,43452,B5,G6350,S,121522304,13721730,+41.5157923,-082.9809454,"POLYGON ((-83.08698 41.53780, -83.08256 41.537..."
2,43456,43456,B5,G6350,S,9320975,1003775,+41.6318300,-082.8393923,"MULTIPOLYGON (((-82.83558 41.71082, -82.83515 ..."
3,43457,43457,B5,G6350,S,48004681,0,+41.2673301,-083.4274872,"POLYGON ((-83.49650 41.25371, -83.48382 41.253..."
4,43458,43458,B5,G6350,S,2573816,39915,+41.5304461,-083.2133648,"POLYGON ((-83.22229 41.53102, -83.22228 41.532..."

In [12]:
# get the DFW zipcodes from the webpage below
url = 'http://www.usa.com/dallas-fort-worth-arlington-tx-area-zip-code-and-maps.htm'
r = requests.get(url)
page = BeautifulSoup(r.text,'html.parser')
tags = page.select('div#rList4')[0].find_all('u')
dfw_metro_zipcodes=[tag.text.strip().split(",")[0] for tag in tags]

In [15]:
dfw_mask = us_geo['ZCTA5CE10'].isin(dfw_metro_zipcodes)
us_geo[dfw_mask]

,ZCTA5CE10,GEOID10,CLASSFP10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
178,75098,75098,B5,G6350,S,85315034,20354151,+33.0121346,-096.5349358,"POLYGON ((-96.60198 33.01127, -96.60061 33.011..."
179,75101,75101,B5,G6350,S,2130983,0,+32.2700320,-096.7024944,"POLYGON ((-96.71534 32.27898, -96.71297 32.280..."
182,75104,75104,B5,G6350,S,101138796,643670,+32.5848142,-096.9723118,"POLYGON ((-97.06551 32.54908, -97.06427 32.549..."
186,75114,75114,B5,G6350,S,112014042,1126841,+32.6105754,-096.4442563,"POLYGON ((-96.50103 32.49728, -96.50101 32.497..."
187,75115,75115,B5,G6350,S,56804463,85455,+32.5994271,-096.8640746,"POLYGON ((-96.90840 32.61879, -96.90560 32.618..."
...,...,...,...,...,...,...,...,...,...,...
21221,76266,76266,B5,G6350,S,311415822,27787497,+33.3728272,-097.2132580,"POLYGON ((-97.38468 33.39370, -97.38459 33.396..."
21719,76651,76651,B5,G6350,S,267517314,2756123,+32.1777102,-096.8511836,"POLYGON ((-97.00035 32.21227, -96.99892 32.213..."
21732,76670,76670,B5,G6350,S,181140306,1844111,+32.1360180,-096.9889628,"POLYGON ((-97.08465 32.12607, -97.08459 32.126..."
31168,75469,75469,B5,G6350,S,79760093,596630,+33.4214093,-095.8106044,"MULTIPOLYGON (((-95.78174 33.40623, -95.78165 ..."
31184,75474,75474,B5,G6350,S,277958706,61918562,+32.9240046,-096.1094327,"POLYGON ((-96.25032 32.93560, -96.25014 32.939..."

In [ ]:
https://www2.census.gov/geo/tiger/TIGER2019/ZCTA5/tl_2019_us_zcta510.zip